#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 2011 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     Allrun
#
# Description
#
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# logReport <logfile>
# Extracts useful info from log file.
    echo "Generating new mesh..."
    rm -r constant/polyMesh   #remove old mesh
    mkdir constant/polyMesh   #create dir to store mesh
    rm -r 0		       #remove old init cond
    cp -r 0.org 0             #copy boundary conditions into 0
    runApplication blockMesh  #generate blockMesh
    application=$(getApplication)      # Set application name  
    runApplication setFields    #setFields
    runApplication $application #run solver according to controlDict
    paraFoam			 #run visualizer


# ----------------------------------------------------------------- end-of-file
